### ISSUE TITLE
Problem with boilerplate

### ISSUE THREAD

**Issue by kylecoberly** [learn-co-curriculum/fewpjs-fetch-lab#15]
```
function renderBooks(json) {
  const main = document.querySelector('main')
  json.forEach(book => {
    const h2 = document.createElement('h2')
    h2.innerHTML = `<h2>${book.name}</h2>`
    main.appendChild(h2)
  })
}
```

Some problems with this:

* Calling `.json()` doesn't turn a response into JSON- it turns a JSON string into a JS object. This function should take in something like `books`.
* Setting the innerHTML of an h2 to an h2 nests them: `<h2><h2>A Tale of Two Cities</h2></h2>`

**Comment by maxwellbenton** [comment]
Hey @kylecoberly,

Thanks for this feedback. I've updated the starter code to use `books` and removed the extra h2 tags being set with `innerHTML`. This issue should now be resolved.
