### ISSUE TITLE
Issue with learn and mocha –– `results`: undefined method`[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by kylejb** [learn-co-curriculum/fewpjs-fetch-lab#17]
I am flagging the below as an issue because this lab seems to be an outlier.

- **Events Leading to Error**
running `learn` on my system consistently produces this error:

- **Error Message**
```/Users/home/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/strategies/mocha.rb:42:in `results': undefined method `[]' for nil:NilClass (NoMethodError)```

- **Additional Testing**
Even after completing the assignment correctly (_confirmed by comparing my code with the solutions branch_), `learn` throws the same error; I initially suspected the `results` error may have relied upon completion of the assignment to populate the test's `results` method with an array of data from Game of Throne's API.

EDIT: 
- **Temporary Fix**: I was able to get around the issue by commenting out Flatiron's unit test file, running `learn`, and then running `npm audit fix`.

**Comment by lizbur10** [comment]
Hi there! I'm sorry you ran into this problem! I haven't been able to recreate it, so I'm going to close this issue.

Cheers 💙
