### ISSUE TITLE
Main tag is required in index.js but missing in index.html

### ISSUE THREAD

**Issue by Joshua-Miles** [learn-co-curriculum/fewpjs-fetch-lab#6]
Main tag is required in index.js but missing in index.html

**Comment by jenmyers** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
